#
# Launch a jupyter notebook on ~/Desktop with `all`.
# Copy backup scripts to Desktop with `restore`.
#

all:
	jupyter-3.7 notebook ~/Desktop

restore:
	cp -rf ~/Desktop/Highlights_Der_Physik_2019/notebooks/* ~/Desktop/
